const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "PRABATH-MD~nYVGjQgJ#lnjlhaRwqmxhdKF_3Znl1_dBKRCDpY1DTSw7Mk_SvIQ"
const SESSION_ID = "94761167172"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
