const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "94761167172"
const SESSION_ID = "PRABATH-MD~hqUSXApY#bl3qdYiQjrICbdNKypkTJ4yWbSENKH9dsDUSxEKEJxQ"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
