const GITHUB_AUTH_TOKEN = "oGYnXLcBB0CkI6O6tEl4JAGXZlI0iJ2wat1I"
const BOT_NUMBER = "94761167172"
const SESSION_ID = "PRABATH-MD~hqUSXApY#bl3qdYiQjrICbdNKypkTJ4yWbSENKH9dsDUSxEKEJxQ"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
